= A minimally viable wiki written with Vert.x

This is a fork of the Vert.x developer guide found here https://vertx.io/docs/guide-for-java-devs/ and https://github.com/vert-x3/vertx-guide-for-java-devs/. This guide offers a good peek at most of the Vert.x capabilities by following a relatively simple usecase of building a wiki. However the guide has now been officially deprecated https://github.com/vert-x3/vertx-guide-for-java-devs/pull/96 & https://github.com/vert-x3/vertx-guide-for-java-devs/pull/97 as it was mainly based on version 3.x and several modules used in the code will no longer be actively maintained. 

Personally it has always been useful to have a guide which one could follow along and learn new constructs. Hence this fork. While we use some the original building blocks and have refactored it to work with Vert.x v4.2 there are a few changes from the original guide

= Changes
1. I intend to refactor only relevant portions of the original guide, leaving out some steps e.g. front end or authentication pieces for now.
2. The earlier guide had all steps as folders. Instead we have a separate branch for each of the step
3. The `src/README.md` will have key call outs on what the step intends to achieve
4. Change the callback heavy code to one which uses `Future compositions`

= The Application
We are going to start with a first iteration and the simplest code possible to have a wiki written with Vert.x.  While the next iterations will introduce more elegance into the code base as well as proper testing, we will see that quick prototyping with Vert.x is both a simple and a realistic target.Our wiki will use server-side rendering of HTML pages and data persistence through a JDBC connection. To do so, we will use the following libraries.

1. http://vertx.io/docs/vertx-web/java/[Vert.x web] to create HTTP servers, routing, handling of request payloads, etc.
2. http://vertx.io/docs/vertx-jdbc-client/java/[Vert.x JDBC client] to provide an asynchronous API over JDBC.
3. http://freemarker.org/[Apache FreeMarker] to render server-side pages as it is an uncomplicated template engine.
4. https://github.com/rjeschke/txtmark[Txtmark] to render Markdown text to HTML, allowing the edition of wiki pages in Markdown.

= Bootstrapping a Vert.x project

This guide makes the choice of using https://maven.apache.org[Apache Maven] as the build tool, primarily because it is very well integrated with the major integrated development environments. You can equally use another build tool such as https://gradle.org/[Gradle].

Vert.x offers an easy way to bootstrap project via https://start.vertx.io/. Simply specify the dependencies, download the zip file, unzip and you should be ready to go. The project offers a sample verticle as well as a unit test. You can safely delete all `.java` files beneath `src/` to hack on the wiki, but before doing so you may test that the project builds and runs successfully:

    mvn package exec:java

You will notice that the Maven project `pom.xml` does 2 interesting things:

1. it uses the https://maven.apache.org/plugins/maven-shade-plugin/[Maven Shade Plugin] to create a single Jar archive with all required dependencies, suffixed by `-fat.jar`, also called _"a fat Jar"_, and
2. it uses the http://www.mojohaus.org/exec-maven-plugin/[Exec Maven Plugin] to provide the `exec:java` goal that in turns starts the application through the Vert.x `io.vertx.core.Launcher` class. This is actually equivalent to running using the `vertx` command-line tool that ships in the Vert.x distribution.

Finally, you will notice the presence of the `redeploy.sh` and `redeploy.bat` scripts that you can alternatively use for automatic compilation and redeployment upon code changes.
Note that doing so requires ensuring that the `VERTICLE` variable in these scripts matches the main verticle to be used.

= Anatomy of a verticle
All Vert.x verticles extends `io.vertx.core.AbstractVerticle`, the base class for verticles that mainly provides:
1. life-cycle `start` and `stop` methods to override,
2. a _protected_ field called `vertx` that references the Vert.x environment where the verticle is being deployed,
3. an accessor to some configuration object that allows passing external configuration to a verticle.

To get started our verticle can just override the `start` method as follows:

[source,java]
----
public class MainVerticle extends AbstractVerticle {

  @Override
  public void start(Promise<Void> promise) {
    promise.complete();
  }
}
----

There are 2 forms of `start` (and `stop`) methods: 
* 1 with no argument 
* 1 with a _promise_ object reference. 

The no-argument variants imply that the verticle initialization or house-keeping phases always succeed unless an exception is being thrown. The variants with a _promise_ object provide a more fine-grained approach to _eventually_ signal that operations succeeded or not. Indeed, some initialization or cleanup code may require asynchronous operations, so reporting via a _promise_ object naturally fits with asynchronous idioms.

NOTE: A promise has a `future()` method which eventually holds the result of an asynchronous operation.

# A word on Vert.x promise / future objects and callbacks
Vert.x futures are not JDK futures: they can be composed and queried in a non-blocking fashion. They shall be used for simple coordination of asynchronous tasks, and especially those of deploying verticles and checking if they were successfully deployed or not. 

The Vert.x core APIs are based on callbacks to notify of asynchronous events. The seasoned developer will naturally think that this opens the door to the so-called _"callback hell"_ where multiple levels of nested callbacks render the code difficult to comprehend as illustrated by this fictional code:

[source,java]
----
foo.a(1, res1 -> {
  if (res1.succeeded()) {
    bar.b("abc", 1, res2 -> {
      if (res.succeeded()) {
         baz.c(res3 -> {
           dosomething(res1, res2, res3, res4 -> {
               // (...)
           });
         });
      }
    });
  }
});
----

The previous versions of this guide used callbacks. However we will be using __Future composure__ in these examples.

= Running the application

At this stage we have a working, self-contained wiki application.

To run it we first need to build it with Maven:

    $ mvn clean package

Since the build produces a Jar with all required dependencies embedded (including Vert.x and a JDBC database), running the wiki is as simple as:

    $ java -jar target/wiki-step-1-1.3.0-SNAPSHOT-fat.jar

You can then point your favorite web browser to http://localhost:8080/ and enjoy using the wiki.

